---
http_interactions:
- request:
    method: post
    uri: https://api.cnova.com/api/v2/loads/products
    body:
      encoding: UTF-8
      string: !binary |-
        H4sIAHJlS1YAAz2OQUvDQBCF/0qY85KatlbNQSi0oFBKlIKHksMkGTcjm026
        OysG8b+7LNbbzPfevDfnb/BkDFt9YjEEJey/xGH2GpoZFHTkW8eT8Gj/pW31
        nLG9OhqHtovajjULmqxCTT7y/fYYabFcrW83d/cp6h2DkcpxG2uKGwUeDf2t
        DwpaFNKjmw/sBcoznMgLPcYyqBW8Ees+4kLBgayWHsplpNylKdKnq2GtAD+R
        DTaGXgJaYZnTHQ/ps5jci0zlYpHAcAloLoFc3o5D3rhE849JQ/1T/wJJF+Ym
        HQEAAA==
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/gzip
      Client-Id:
      - F6Y2DJkFtLL2
      Access-Token:
      - bEptWFqM72U0
      Content-Length:
      - '229'
      User-Agent:
      - Ruby
  response:
    status:
      code: 429
      message: Too Many Requests
    headers:
      Content-Type:
      - text/plain
      Date:
      - Tue, 17 Nov 2015 17:35:46 GMT
      Server:
      - Apache-Coyote/1.1
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: Current rate (2) exceeds the maximum rate for this API (1)
    http_version: 
  recorded_at: Tue, 17 Nov 2015 17:35:46 GMT
recorded_with: VCR 2.9.3
